version: "3"
services:
  ecs-monitor:
    image: ecsmonitor
    volumes:
      - ../:/opt/monitor-ecs
    ports:
      - "5005:5000"
    environment:
      - FLASK_DEBUG=True
      - FLASK_APP=main.py
    #command: /usr/bin/flask run --host=0.0.0.0
    command: tail -f /dev/null
